In [ ]:
Conditio of Multilabel Classification :->
    1. Last layers output/number_of_neuron must be same as total number of layers.
    2. 

In [21]:
import numpy as np

from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import RepeatedKFold
from sklearn.metrics import accuracy_score

import keras
from keras.models import Sequential
from keras.layers import Dense


### Building Dataset

In [12]:
X, y = make_multilabel_classification(n_samples=2000, n_features=10, n_classes=3, n_labels=2, random_state=1)

In [13]:
print(f"Shape of X is :{X.shape}, Shape of y is :{y.shape}")

Shape of X is :(2000, 10), Shape of y is :(2000, 3)


In [17]:
for row in range(5):
    print(X[row])

[ 3.  3.  6.  7.  8.  2. 11. 11.  1.  3.]
[7. 6. 4. 4. 6. 8. 3. 4. 6. 4.]
[ 5.  5. 13.  7.  6.  3.  6. 11.  4.  2.]
[1. 1. 5. 5. 7. 3. 4. 6. 4. 4.]
[ 4.  2.  3. 13.  7.  2.  4. 12.  1.  7.]


In [18]:
for label in range(5):
    print(y[label])

[1 1 0]
[0 0 0]
[1 1 0]
[1 1 1]
[0 1 0]


### Smart Way

In [42]:
def get_dataset():
    X, y = make_multilabel_classification(n_samples=1000, n_features=10, n_classes=3, n_labels=2, random_state=1)
    return X, y


In [43]:
def get_model(n_inputs, n_outputs):
    model = Sequential()
    model.add(Dense(20, input_dim=n_inputs, kernel_initializer='he_uniform', activation='relu'))
    model.add(Dense(n_outputs, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam')
    return model


In [48]:
def train(X,y):
    results = list()
    n_inputs, n_outputs = X.shape[1], y.shape[1]
    cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
    for i, (train_x, test_x) in enumerate(cv.split(X)):
        X_train, X_test = X[train_x], X[test_x] 
        Y_train, Y_test = y[train_x], y[test_x]
        
        model = build_model(n_inputs, n_outputs)
        model.fit(X_train, Y_train, verbose=0, epochs=100)
        yhat = model.predict(X_test)
        yhat = yhat.round()
        acc = accuracy_score(Y_test, yhat)
        print(f'Accuracy score in folds {i} is :{acc}')
        results.append(acc)
    return model, results 


        

In [49]:
X, y = build_dataset()

model, result = train(X, y)

Accuracy score in folds 0 is :0.855
Accuracy score in folds 1 is :0.845
Accuracy score in folds 2 is :0.825
Accuracy score in folds 3 is :0.8
Accuracy score in folds 4 is :0.785
Accuracy score in folds 5 is :0.845
Accuracy score in folds 6 is :0.81
Accuracy score in folds 7 is :0.805
Accuracy score in folds 8 is :0.855
Accuracy score in folds 9 is :0.75
Accuracy score in folds 10 is :0.88
Accuracy score in folds 11 is :0.805
Accuracy score in folds 12 is :0.785
Accuracy score in folds 13 is :0.81
Accuracy score in folds 14 is :0.835
Accuracy score in folds 15 is :0.8
Accuracy score in folds 16 is :0.835
Accuracy score in folds 17 is :0.805
Accuracy score in folds 18 is :0.815
Accuracy score in folds 19 is :0.8
Accuracy score in folds 20 is :0.84
Accuracy score in folds 21 is :0.84
Accuracy score in folds 22 is :0.76
Accuracy score in folds 23 is :0.825
Accuracy score in folds 24 is :0.825
Accuracy score in folds 25 is :0.85
Accuracy score in folds 26 is :0.84
Accuracy score in folds 27

In [50]:
print(f"Accuracy : {np.mean(result)}, {np.std(result)}")

Accuracy : 0.8208333333333333, 0.028168638984200516


In [51]:
row = [3, 3, 6, 7, 8, 2, 11, 11, 1, 3]
newX = np.asarray([row])
yhat = model.predict(newX)

In [52]:
yhat

array([[0.9976742 , 0.99445236, 0.004444  ]], dtype=float32)